### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by imshubbh** [vishal554/Django-Quiz-App#1]
Hey **Vishal**,  you can save EMAIL_HOST_PASSWORD is system environments or any other file and inherit in settings.py of project. And remove that file while uploading to GitHub.

https://github.com/vishal554/Django-Quiz-App/blob/9de47d6fd1a990ad2bd4c0974426bcb4213e6ab9/Quiz/settings.py#L139-L144

**Comment by vishal554** [comment]
Thanks for the help. I have fixed it now
